### ISSUE TITLE
Gives me error in gvim windows 10

### ISSUE THREAD

**Issue by eduardoarandah** [inkarkat/vim-ExtractMatches#1]
Gives me error in gvim windows 10

![imagen](https://user-images.githubusercontent.com/4065733/64368125-4394e980-cfdf-11e9-8205-351162ca997e.png)

I don't know how to make this report more specific. 
I was trying to extract what's inside `scr=""` in the html

Version:

![imagen](https://user-images.githubusercontent.com/4065733/64368156-560f2300-cfdf-11e9-9af2-3edec343f9d8.png)

**Comment by inkarkat** [comment]
You also need to install the [ingo-library plugin](http://www.vim.org/scripts/script.php?script_id=4433) (or via [GitHub](https://github.com/inkarkat/vim-ingo-library)). It's listed in the [dependencies](https://github.com/inkarkat/vim-ExtractMatches#dependencies). This library contains common autoload functions that are used by almost all of my plugins; it avoids code duplication and versioning issues.
