### ISSUE TITLE
Pasting after a yank uses the wrong register?

### ISSUE THREAD

**Issue by hejops** [inkarkat/vim-ExtractMatches#3]
**Describe the bug**

Yanking lines with `GrepToReg` puts them in the unnamed register (correct number of lines reported, and verified with `:registers`), but `p/P` doesn't paste these lines. Instead, `p` seems to paste the contents of the `+` register, so I have to use `""p`.
Is this behaviour intended? I might have misunderstood the concept of the unnamed register, but I hope that isn't the case.

**How to Reproduce**

```
:'<,'>GrepToReg/hello/["]
""p
```

**Expected Behavior**

```
:'<,'>GrepToReg/hello/["]
p
```

**Environment**
 - Plugin version: revision 6a7938d
 - Dependency versions: ingo-library revision 8845fbf
 - Vim version 8.1
 - OS: Ubuntu 20.04.2 LTS
 - Install method: vim-plug

**Comment by inkarkat** [comment]
I think you have `:set clipboard=unnamedplus` (you can check with `:set clipboard?`); then, any built-in operations (like pasting with `p`) will default to the clipboard register (`+`), and the unnamed register (which the plugin writes to if no register is passed) will need to be explicitly specified (`""p`) - just like you describe it.

(_I think it would be nice if the plugin would automatically default to `+`, too, just like built-in commands like `:yank` do. Unfortunately, that has to be explicitly implemented; the register-handling functions in Vimscript do not handle this automatically._)

**Comment by hejops** [comment]
Ah, I see. It works as expected when I specify the `+` register. Thanks.

(Maybe this should be mentioned in the readme; I think `unnamedplus` is a rather common setting)

**Comment by inkarkat** [comment]
> (Maybe this should be mentioned in the readme; I think unnamedplus is a rather common setting)

Many people would still miss it there. And this is kind of like every plugin that deals with registers behaves. It would be nice if there were a warning at [`:help 'clipboard'`](https://vimhelp.appspot.com/options.txt.html#%27clipboard%27): _Note that most plugins will still default to the unnamed register (so get used to explicitly passing `+`, or maybe don't set this option if that bothers you.)_

From the users's perspective, the best solution would be if the plugin would also default to the clipboard register, to be consistent with built-in commands (like `:yank`). As I've mentioned before, I'm thinking of implementing that - but to do this in a robust way and for all of my plugins, this isn't trivial, unfortunately.
